friends/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from haystack.views import SearchView
from friends import views

urlpatterns = patterns('',
                       url(r'^$', views.HomeView.as_view(), name='home'),
                       url(r'^connect$', login_required(views.ConnectView.as_view()), name='connect'),
                       url(r'^profile$', login_required(views.ProfileView.as_view()), name='profile'),
                       url(r'^checkprofile$', views.checkprofile, name='checkprofile'),
)

friendship/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'friendship.views.home', name='home'),
                       # url(r'^friendship/', include('friendship.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^friends/', include('friends.urls', namespace='friends')),

                       #for django-allauth
                       url(r'^accounts/', include('allauth.urls')),

)

friends/models.py
from django.db import models
from django.contrib.auth.models import User
from allauth.account.signals import user_signed_up, user_logged_in

#this is a simple model to store all of the activities and the group they fall in
from django.dispatch import receiver


class Activity(models.Model):
    name = models.CharField(max_length=200)
    group = models.CharField(max_length=200)
    date = models.DateTimeField('date added')
    #users = models.ManyToManyField(User)

    def __unicode__(self):
        return self.name


class Profile(models.Model):
    #choices
    SEX_CHOICES = (("M", 'male'), ("F", 'female'))
    REL_CHOICES = (
        ('S', 'single, no kids'),
        ('P', 'single, with kid(s)'),
        ('R', 'in a relationship, no kids'),
        ('K', 'in a relationship, with kid(s)'),
    )
    ED_CHOICES = (
        ('H', 'high school'),
        ('C', 'college'),
        ('A', 'advanced degree'),
    )
    PER_CHOICES = (
        ('I', 'introverted'),
        ('E', 'extroverted')
    )


    #model fields
    user = models.OneToOneField(User)
    # age = models.IntegerField(max_length=2)
    # sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    # rstatus = models.CharField(max_length=1, choices=REL_CHOICES)
    # education = models.CharField(max_length=1, choices=ED_CHOICES)
    # personality = models.CharField(max_length=1, choices=PER_CHOICES)
    # blurb = models.CharField(max_length=200)
    # date = models.DateTimeField('date added')

    #many to many relationship to User in order to track who likes who and who is liked by who
    likes = models.ManyToManyField("self", related_name="liked by")

    #many to many relationship with Activity
    activities = models.ManyToManyField(Activity, null=True)

    color = models.CharField(max_length=20)

    def __unicode__(self):
        return self.user.username


    #profile is considered complete if user likes at least one activity and has answered favorite color question
    def profile_complete(self):
        print "checking if profile is complete"
        for a in self.activities.all():
            print a.name
        if len(self.activities.all()) > 2 and self.color != "":
            return True

        return False

# right after someone signs up, create a new profile for them
# @receiver(user_signed_up):
# def create_profile(request, user, **kwargs):
#     print "Create profile for", user
#     p = Profile(user=user)
#     p.save()


class Location(models.Model):
    homezip = models.CharField(max_length=5)
    workzip = models.CharField(max_length=5)
    date = models.DateTimeField('date added')

friends/forms.py
from itertools import chain
from django.dispatch import receiver
from django.forms import ModelForm
from django.utils import timezone
from django import forms
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe
from haystack.forms import SearchForm, ModelSearchForm
from haystack.inputs import AutoQuery
from haystack.query import SearchQuerySet
from friends.models import Profile, Activity
from django.forms.models import inlineformset_factory, BaseInlineFormSet


#custom widget so Activities checkboxes can be organized by group
class ActivitiesByCategory(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)

        #the div that stores the main output
        output = [u'<div>']

        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])

        categories = Activity.objects.values('group').distinct()
        for category in categories:
            groupname = category['group']
            output.append(u'<h3>%s</h3>' % groupname)
            #div storing choices under each category
            output.append(u'<div>')
            del self.choices
            self.choices = []
            activities = Activity.objects.filter(group=groupname)
            for activity in activities:
                self.choices.append((activity.id, activity.name))
            for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
                if has_id:
                    final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                    label_for = u' for="%s"' % final_attrs['id']
                else:
                    label_for = ''
                cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
                option_value = force_unicode(option_value)
                rendered_cb = cb.render(name, option_value)
                option_label = conditional_escape(force_unicode(option_label))
                output.append(
                    u'<div class="checkbox"><label%s>%s %s</label></div>' % (label_for, rendered_cb, option_label))
            output.append(u'</div>')
        output.append(u'</div>')
        return mark_safe(u'\n'.join(output))


class ActivitiesForm(forms.ModelForm):
    #since i want to override the widget to checkbox, i need to override the entire field
    activities = forms.ModelMultipleChoiceField(queryset=Activity.objects.all(),
                                                widget=ActivitiesByCategory,
                                                required=True)

    class Meta:
        model = Profile
        exclude = ['user', 'likes']

friends/views.py
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import UpdateView
from django.views.generic.base import View, TemplateResponseMixin, TemplateView
from friends.forms import ActivitiesForm
from friends.models import Activity, Profile


class HomeView(TemplateView):
    template_name = "friends/home.html"


class ConnectView(TemplateView):
    template_name = 'friends/connect.html'

    def get_context_data(self, **kwargs):
        context = super(ConnectView, self).get_context_data(**kwargs)
        #context['user'] = request.user
        context['activities'] = Activity.objects.all
        context['times'] = {"Friday", "Saturday", "Sunday", "Monday"}
        return context


class ProfileView(UpdateView):
    template_name = "friends/profile.html"
    form_class = ActivitiesForm
    model = Profile
    success_url = '/friends'#this is required

    def get_object(self, queryset=None):
        return self.request.user.profile


def checkprofile(request):
    #right after someone signs up, create a new profile for them if they don't have one
    if not hasattr(request.user, 'profile'):
        p = Profile(user=request.user)
        p.save()
    else:
        p = request.user.profile
    if p.profile_complete():
        return HttpResponseRedirect("/friends/connect")
    return HttpResponseRedirect("/friends/profile")

friends/templates/friends/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Friendship</title>
    <meta name="description" content="">
    <meta name="author" content="Yin Li">
    <link rel="stylesheet" href="{% static "bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "grid.css" %}">
    <link rel="stylesheet" href="{% static "navbar.css" %}">
    <link rel="stylesheet" href="{% static "jumbotron.css" %}">
</head>

<body>
<div class="container">
      <!-- Static navbar -->
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'friends:home' %}">Friends App</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <!--following links should only show up if folks are logged in-->
                <li class="active"><a href="{% url 'friends:connect' %}">Connect</a></li>
                <li><a href="{% url 'friends:profile' %}">Profile</a></li>
                <li><a href="{% url 'friends:home' %}">Availability</a></li>
                <li><a href="{% url 'friends:home' %}">{{ user.username }}</a></li>
                <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'account_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div> <!-- container -->

{% block content %}Empty page{% endblock %}

</body>

</html>

friends/templates/friends/connect.html
{% extends "friends/base.html" %}

{% block content %}

<!--dropdown to select activity-->
<span> I want to
<select form="connectform">
    {% for act in activities %}
        <option value="{{ act.name }}">{{ act.name }}</option>
    {% endfor %}
</select>
 on
<select>
    {% for t in times %}
        <option value="{{ t }}">{{ t }}</option>
    {% endfor %}
</select>

<form action="#" id="connectform">
  <input type="submit">
</form>
</span>

    <!-- this is some info pulled from a facebook account that can be formatted/displayed -->
    {% for account in user.socialaccount_set.all %}
        <h2 style="text-transform:capitalize;">{{ account.provider }} account data</h2>
        <p><img width="50" height="50" src="{{ account.get_avatar_url }}" /></p>
        <p>UID: <a href="{{account.extra_data.link }}">{{ account.uid }}</a></p>
        <p>Username: {{ account.extra_data.username }}</p>
        <p>First Name: {{ account.extra_data.first_name }}</p>
        <p>Last Name: {{ account.extra_data.last_name }}</p>
        <p>Email: {{ account.extra_data.email}}</p>
        <p>Profile Link: <a href="{{ account.extra_data.link }}">{{ account.extra_data.link }}</a></p>
    {% endfor %}
{% endblock %}

friends/templates/friends/home.html
{% extends "friends/base.html" %}

{% block content %}
<h1>Welcome to Friends App</h1>
{% load socialaccount %}

<!--if no one is logged in, display login link-->
{% if not user.is_authenticated %}
    {% providers_media_js %}
    <a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
{% endif %}

{% endblock %}

friends/templates/friends/interests.html
{% extends "friends/base.html" %}

{% block content %}

<form action="{% url 'friends:interests' user.profile.id %}" method="post">{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

friends/templates/friends/profile.html
{% extends "friends/base.html" %}

{% block content %}

<form action="{% url 'friends:profile' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}